package edu.iastate.cs228.hw3;

import java.io.FileNotFoundException;
import java.util.Arrays;
import java.util.Scanner;


public class PuzzleSolver 
{
	/**
	 *  Read an initial state from an file.  Solve the eight puzzle using two heuristics based on 
	 *  the number of mismatched tiles and the Manhattan distance.  Each solution is printed out 
	 *  as a sequence of states, generated by single moves, from the initial state to the goal
	 *  state. If no solution exists, report it.  
	 * 
	 * @param args
	 * @throws FileNotFoundException if the input file does not exist 
	 * @throws IllegalArgumentException if the initial state from the file is not in the correct format
	 */
	@SuppressWarnings("static-access")
	public static void main(String[] args) throws FileNotFoundException, IllegalArgumentException
	{
		// Read an initial board configuration from a file.  
		// Call EightPuzzle.solve8puzzle() to solve the puzzle. 
		int[][] board = {{1,2,3},{6,5,7},{8,4,0}};
		State init = new State(board);
		
		//Check init.board
		System.out.println(Arrays.deepToString(init.board));
		
		EightPuzzle puzzle = new EightPuzzle();
		System.out.println(puzzle.solve8Puzzle(init));
		
		int[][] board1 = {{4,1,2},{3,5,0},{8,6,7}};
		State init1 = new State(board1);
		EightPuzzle puzzle1 = new EightPuzzle();
		System.out.println(puzzle1.solve8Puzzle(init1));
		
		int[][] board2 = {{1,2,3},{8,0,4},{7,6,5}};
		State init2 = new State(board2);
		EightPuzzle puzzle2 = new EightPuzzle();
		System.out.println(puzzle2.solve8Puzzle(init2));
		
		int[][] board3 = {{4,1,2},{5,3,0},{8,6,7}};
		State init3 = new State(board3);
		EightPuzzle puzzle3 = new EightPuzzle();
		System.out.println(puzzle3.solve8Puzzle(init3));
		
		// You may make it interactive by repeatedly accepting puzzle files and print out 
		// solutions (in a manner similar to Project
		// 1).  (No extra credit but good for debugging 
		// and for the user.)
		Scanner scan = new Scanner(System.in);
		String line = "";
		while (true){
			System.out.println("enter a filename" + "\n" + "to quit, enter: " + " wq");
			line = scan.nextLine();
			if (line.equals("wq")) break;
			State s = new State(line);
			System.out.println(EightPuzzle.solve8Puzzle(s));
		}
		scan.close();
	}
}
